---
- debug:
    msg: "{{ item.volume_ids }}"
  loop: '{{ instances }}'

- name: Create instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ item.security_groups }}'
    network: '{{ instance_network }}'
    volumes: "{{ item.volume_ids }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance
  loop: '{{ instances }}'

- name: set ip address to fact
  set_fact:
    ip_addresses: "{{ ip_addresses|default([]) + [ {'name': item.item.name, 'ip': item.openstack.public_v4} ] }}"
  when: item.openstack is defined
  loop: '{{ os_instance.results }}'

- debug:
    msg: "| ip_addresses ==> {{ ip_addresses }}"

- name: Create inventory file
  copy:
    content: "[all:vars]\nansible_user=ubuntu\n\n[dbServers:children]\ndbMaster\ndbSlave\n\n[dbMaster:children]\ninstance1\n\n[dbSlave:children]\ninstance2\ninstance3\n\n"
    dest: "./inventory/hosts.ini"

- name: set ip addresses to inventory file
  lineinfile:
    line: "[{{ item.name }}]\n{{ item.ip }}\n"
    dest: "./inventory/hosts.ini"
  loop: '{{ ip_addresses }}'

- name: Adding manager1 (leader)
  lineinfile:
    line: "[leader]\n{{ item.ip }}\n"
    dest: "./inventory/hosts.ini"
  when: item.name == "instance1_fresh"
  loop: '{{ ip_addresses }}'

- name: Adding manager2
  lineinfile:
    line: "[managers]\n{{ item.ip }}\n"
    dest: "./inventory/hosts.ini"
  when: item.name == "instance2"
  loop: '{{ ip_addresses }}'

- name: Adding manager3
  lineinfile:
    line: "{{ item.ip }}\n"
    dest: "./inventory/hosts.ini"
  when: item.name == "instance3"
  loop: '{{ ip_addresses }}'

# - name: Adding worker
#   lineinfile:
#     line: "[workers]\n{{ item.ip }}\n"
#     dest: "./inventory/hosts.ini"
#   when: item.name == "instance4"
#   loop: '{{ ip_addresses }}'