
- name: Check folders
  become: yes
  stat:
    path: '/etc/systemd/system/docker.service.d'
  register: docker_service_dir

- name: Create directory
  become: yes
  file:
    path: '/etc/systemd/system/docker.service.d'
    recurse: yes
    state: directory
  when: docker_service_dir.stat.exists == false

- name: Create directory 2
  become: yes
  file:
    path: '~/.docker'
    recurse: yes
    state: directory

- name: change docker proxy | step 2
  become: yes
  copy:
    content: "[Service]\nEnvironment=\"HTTP_PROXY={{ proxy_address }}\"\nEnvironment=\"NO_PROXY={{no_proxy_address}}\""
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf

- name: change docker proxy | step 3
  become: yes
  template:
    src: "docker.service.j2"
    dest: "/lib/systemd/system/docker.service"
    owner: root
    group: root
    force: yes

- name: change docker proxy | step 4
  become: yes
  command: systemctl daemon-reload

- name: change docker proxy | step 5
  become: yes
  command: systemctl restart docker

- name: add docker config file | step 6
  become: yes
  copy:
    content: '{"proxies":{"default":{ "httpProxy":"http://wwwproxy.unimelb.edu.au:8000", "httpsProxy":"http://wwwproxy.unimelb.edu.au:8000","noProxy":"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"}}}'
    dest: ~/.docker/config.json

- name: Open docker daemon
  become: yes
  file:
    path: /var/run/docker.sock
    owner: root
    group: root
    mode: '666'