version: "3"
services:
  image: "ibmcom/couchdb3:3.0.0"
      restart: always
      ports:
        - "5984:5984"
        - "5986:5986"
        - "4369:4369"
        - "9100-9200:9100-9200"
      volumes:
            - ./data/master/data:/opt/couchdb/data
      environment:
        - COUCHDB_USER=user
        - COUCHDB_PASSWORD=pass
      container_name: 'couch{{ item.name }}'