---
- hosts: 
    - instance1_fresh
    - instance2
    - instance3
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true
  roles:
    - role: install-environments
    - role: network-penetration
    - role: mount-volume
    # - role: couchdb-cluster
