---
#############################################
#                  Common                   #
#############################################
proxy_address: http://wwwproxy.unimelb.edu.au:8000
no_proxy_address: "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au"
remote_working_directory: /home/ubuntu/COMP90024

#############################################
#                 CouchDB                   #
#############################################
couchdb_version: 2.3.0
couchdb_config_path: /home/ubuntu/couchdb/etc
couchdb_share: 4
couchdb_replica: 3
cluster_cookie: 'hello'
cluster_communication_port_min: 9100
cluster_communication_port_max: 9102

#############################################
#                  Docker                   #
#############################################
enable_docker_remote_control: true

#############################################
#                 Backend                   #
#############################################


#############################################
#                 Machine learning          #
#############################################
backend_server_host: 172.26.38.1
backend_server_port: 8080
trained_tweet_api: "/api/tweet/trained/"
untrained_tweet_api: "/api/tweet/untrained/"
pic_tweet_api: "/api/tweet/pic/"
log_file_path: "logs/coconut_image_recong.log"
food179_checkpoints: "checkpoints/food179_resnet101_sgd_v3.pth_best.pth"
nsfw_checkpoints: "checkpoints/nsfw_resnet101_sgd_v3.pth_best.pth"
# server_rest_time: 30
# batch_size": 20
